# Generated by Django 4.2.7 on 2024-12-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=50, verbose_name='楼栋号')),
                ('unit', models.CharField(max_length=50, verbose_name='单元号')),
                ('room', models.CharField(max_length=50, verbose_name='房间号')),
                ('area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='面积(平方米)')),
                ('status', models.CharField(choices=[('occupied', '已入住'), ('vacant', '空置')], default='vacant', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '房产信息',
                'verbose_name_plural': '房产信息',
            },
        ),
    ]
