# Generated by Django 4.2.7 on 2024-12-06 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='费用类别名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('unit', models.CharField(max_length=20, verbose_name='计费单位')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '收费类别',
                'verbose_name_plural': '收费类别',
            },
        ),
        migrations.CreateModel(
            name='ChargeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('billing_date', models.DateField(verbose_name='账单日期')),
                ('due_date', models.DateField(verbose_name='截止日期')),
                ('status', models.CharField(choices=[('pending', '待缴费'), ('paid', '已缴费'), ('overdue', '已逾期')], default='pending', max_length=20, verbose_name='状态')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='缴费日期')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charges.chargecategory', verbose_name='费用类别')),
            ],
            options={
                'verbose_name': '收费记录',
                'verbose_name_plural': '收费记录',
            },
        ),
    ]
