# Generated by Django 4.2.7 on 2024-12-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='统计日期')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='总金额')),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='已缴金额')),
                ('pending_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='待缴金额')),
                ('overdue_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='逾期金额')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '收费统计',
                'verbose_name_plural': '收费统计',
            },
        ),
    ]
